### ISSUE TITLE
setData 列表更新如果无数据（null），原来被渲染到页面上的列表不会移除

### ISSUE THREAD

**Issue by foxhunter** [epaii/epii.js#5]
第一步，由setData初始化了列表循环数据，并已经渲染到了页面上。
第二步，后续因为更新原因，列表后端获取到的数据为空（null），此时会出现两个问题：如果没有设置r-empty,渲染会在console中报错，如果设置了empty，报错没有了，empty也显示了，但是原来的列表数据还在页面中没有被删除。

**Comment by epaii** [comment]
已收到问题，尽快修复 谢谢

**Comment by epaii** [comment]
已经修复，感谢您的支持。 示例代码： https://epaii.github.io/epii.js/demo/docs_html/demo10.html

**Comment by foxhunter** [comment]
作者这火速得我无言以对啊 哈哈！ 更新去咯！
