### ISSUE TITLE
建议：列表支持下单纯的字符串列表

### ISSUE THREAD

**Issue by foxhunter** [epaii/epii.js#6]
目前我看代码列表似乎都是 基于 object 数组的。然而如果返回的是简单的字符串数组['xxx.jpg','www.jpg']，这种方式 就不好操作了（也可能我没太了解代码不知道是否有其他访问方式）。我目前的解决办法是修改了源代码，因为主要是后台ajax来的，所以遇到list条目typeof是string的，强制转换成{v:'xxx.jpg',i:j+1} ，其中i是对应index做顺序字段。不知道作者有没有更好的解决方式了

**Comment by epaii** [comment]
收到，我们会尽快完善，感谢您的支持

**Comment by epaii** [comment]
已经完善并上线，【如果数据为纯字符串数组，则值用value表示】    示例  https://epaii.github.io/epii.js/demo/docs_html/demo7.html，再次感谢您的支持

**Comment by epaii** [comment]
已经完善并上线，【如果数据为纯字符串数组，则值用value表示】再次感谢您的支持
 示例 https://epaii.github.io/epii.js/demo/docs_html/demo7.html

**Comment by epaii** [comment]
<div id="content">
    <h1 r-data="title" >  </h1>
    <div r-list="users">
        <div>名称<span r-data="name"></span>,年龄<span r-data="age"></span></div>
    </div>
    <div r-list="strings">
        <div>value:<span r-data="value"></span></div>
    </div>
</div>
<script>
    var myepii = epii(document.getElementById("content"));//初始化殷勤，需要制定dom节点 可以是 body

    myepii.setData({
        title: "列表展示",
        users:[
            {name:"张三",age:"12岁"},
            {name:"李四",age:"14岁"}
        ],
        strings:["string1","string2","string3"]
    });

</script>

**Comment by epaii** [comment]
`

<div id="content">
--
  | <h1 r-data="title" >  </h1>
  | <div r-list="users">
  | <div>名称<span r-data="name"></span>,年龄<span r-data="age"></span></div>
  | </div>
  | <div r-list="strings">
  | <div>value:<span r-data="value"></span></div>
  | </div>
  | </div>
  | <script>
  | var myepii = epii(document.getElementById("content"));//初始化殷勤，需要制定dom节点 可以是 body
  |  
  | myepii.setData({
  | title: "列表展示",
  | users:[
  | {name:"张三",age:"12岁"},
  | {name:"李四",age:"14岁"}
  | ],
  | strings:["string1","string2","string3"]
  | });
  |  
  | </script>

`

**Comment by epaii** [comment]
```

<div id="content">
--
  | <h1 r-data="title" >  </h1>
  | <div r-list="users">
  | <div>名称<span r-data="name"></span>,年龄<span r-data="age"></span></div>
  | </div>
  | <div r-list="strings">
  | <div>value:<span r-data="value"></span></div>
  | </div>
  | </div>
  | <script>
  | var myepii = epii(document.getElementById("content"));//初始化殷勤，需要制定dom节点 可以是 body
  |  
  | myepii.setData({
  | title: "列表展示",
  | users:[
  | {name:"张三",age:"12岁"},
  | {name:"李四",age:"14岁"}
  | ],
  | strings:["string1","string2","string3"]
  | });
  |  
  | </script>


```
